#!/bin/bash

export PYTHONPATH=$PYTHONPATH:$WORKSPACE_HOME/GraphAnalyzer2/src:$WORKSPACE_HOME/GraphAnalyzer2/src-scripts

#python -m cProfile -s cumulative $WORKSPACE_HOME/GraphAnalyzer2/src/logparse.py $@

python -m experiment.logparse $@