#!/bin/bash

if [ $1 == "profile" ]
then
    FLAGS=-agentpath:/home/giuliano/Software/netbeans/netbeans-6.8/profiler3/lib/deployed/jdk16/linux/libprofilerinterface.so=/home/giuliano/Software/netbeans/netbeans-6.8/profiler3/lib,5140
    shift
fi

CP="$HOME/workspace/Social_Peer_Sampling/bin:$HOME/workspace/peersim/bin:$HOME/workspace/Utilities/lib/ext-1.1.1.jar:$HOME/workspace/Utilities/lib/jep-2.4.1.jar:$HOME/workspace/extras/bin:$HOME/workspace/Utilities/bin:$HOME/workspace/Utilities/lib/colt-1.2.0.jar:$HOME/workspace/Utilities/lib/google-collect-1.0-rc3.jar:$HOME/workspace/Experiments/bin:$HOME/workspace/CyclonProject/bin:$HOME/workspace/QuickAndDirty/bin peersim.Simulator"

java $FLAGS -Xmx1024m -server -cp $CP "$@"