#!/bin/bash

. $BASH_LIB/common.lib

checkpar 1 $#

TEMPLATE_NAME=$1
OP_DIRECTORY=$PWD

shift

echo Finding template files. 

for i in `find -iname $TEMPLATE_NAME`
do
    PATHLOC=`echo $i | sed 's/\/'$TEMPLATE_NAME'//'`
    CMD="run_std -p $PATHLOC -t $TEMPLATE_NAME $@"
    echo Running $CMD.
    $CMD
done