#!/bin/bash

################################################################################
#
# Syntax:  
# multi_average -t [tag] -s [start_delimiter] -e [end_delimiter] [repetitions] [stem]
#
################################################################################

. ${BASH_LIB}/common.lib

function print_help {
    echo Syntax: $0 [options] [repetitions] [stem]
    echo
    echo Options:
    echo -e "   -t [tag]"
    echo -e "   -s [start_delimiter]"
    echo -e "   -e [end_delimiter] (to be used with -s)"
    exit 1
}

function check_set {
    if [ -z $2 ]
    then 
	echo Mandatory argument $1 is missing. Type $0 -h for help.
	exit 1
    else
	echo Parameter $1 is $2.
    fi
}

#=======================================
# Parses options. 
#=======================================

while getopts "t:s:e:h" o ; do  
    case $o in  
        t ) TAG=$OPTARG;;
        s ) START_DELIMITER=$OPTARG;;  
        e ) END_DELIMITER=$OPTARG;;
	h ) 
	    print_help
	    ;;
	\?)
	    echo "Type $0 -h for help." >&2
	    exit 1
	    ;;
	:)
	    echo "Option -$OPTARG requires an argument. Type $0 -h for help." >&2
	    exit 1
	    ;;
    esac  
done

shift $((OPTIND-1))

check_set "repetitions" $1
check_set "stem" $2

# Determines the mode to operate on.
if [ -n "${TAG+x}" ]
then 
    mode="tag"
fi

if [[ -n "${START_DELIMITER+x}" && -n "${END_DELIMITER+x}" ]]
then
    mode="delimiter"
fi

if [ -n "${mode+x}" ]
then
    : #NOP
else
    mode="raw"
fi

echo Mode is $mode.

# Easier-on-the-eye aliases.
repetitions=$1
stem=$2

#=======================================
# Performs the averaging.
#=======================================

for i in `seq 1 $repetitions`
do
    if [[ $mode = "raw" ]]
    then
	cp $stem-$i.text ${stem}.b

    elif [[ $mode = "tag" ]]
    then
	echo Run tag_extract.
	tag_extract $stem-$i.text $TAG > $stem.b

    elif [[ $mode = "delimiter" ]]
    then
	echo Run extract.
	extract $stem-$i.text $START_DELIMITER $END_DELIMITER > $stem.b
    fi

    step_average $stem $i
done

echo Clean up...
rm $stem.b